# Generated by Django 6.1 on 2026-08-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['teacher_number', 'last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_number',
            field=models.PositiveIntegerField(blank=True, help_text='Numeric teacher number displayed on timetables.', null=True, unique=True),
        ),
    ]
