# Generated by Django 6.1 on 2026-08-15 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subject',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='core.academicyear')),
            ],
            options={
                'db_table': 'grade',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='academics.grade')),
            ],
            options={
                'db_table': 'stream',
                'ordering': ['grade', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('learner_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_groups', to='academics.stream')),
            ],
            options={
                'db_table': 'teaching_group',
                'ordering': ['stream', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LessonRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lessons_per_week', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requirements', to='core.term')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requirements', to='academics.subject')),
                ('teaching_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requirements', to='academics.teachinggroup')),
            ],
            options={
                'db_table': 'lesson_requirement',
                'ordering': ['teaching_group', 'subject'],
            },
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='uq_grade_academic_year_name'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('academic_year', 'code'), name='uq_grade_academic_year_code'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('grade', 'name'), name='uq_stream_grade_name'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('grade', 'code'), name='uq_stream_grade_code'),
        ),
        migrations.AddConstraint(
            model_name='teachinggroup',
            constraint=models.UniqueConstraint(fields=('stream', 'name'), name='uq_teaching_group_stream_name'),
        ),
        migrations.AddConstraint(
            model_name='teachinggroup',
            constraint=models.UniqueConstraint(fields=('stream', 'code'), name='uq_teaching_group_stream_code'),
        ),
        migrations.AddConstraint(
            model_name='teachinggroup',
            constraint=models.CheckConstraint(condition=models.Q(('learner_count__gte', 0)), name='ck_teaching_group_learner_count'),
        ),
        migrations.AddConstraint(
            model_name='lessonrequirement',
            constraint=models.UniqueConstraint(fields=('term', 'teaching_group', 'subject'), name='uq_lesson_requirement_term_group_subject'),
        ),
        migrations.AddConstraint(
            model_name='lessonrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('lessons_per_week__gte', 1)), name='ck_lesson_requirement_lessons_positive'),
        ),
    ]
