# Generated by Django 6.1 on 2026-08-22 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_instructional_groups(apps, schema_editor):
    TeachingGroup = apps.get_model("academics", "TeachingGroup")
    InstructionalGroup = apps.get_model("academics", "InstructionalGroup")
    LessonRequirement = apps.get_model("academics", "LessonRequirement")

    group_map = {}

    for teaching_group in TeachingGroup.objects.all().iterator():
        instructional_group, created = InstructionalGroup.objects.get_or_create(
            teaching_group_id=teaching_group.pk,
            code=teaching_group.code,
            defaults={
                "name": teaching_group.name,
                "learner_count": teaching_group.learner_count,
                "is_active": teaching_group.is_active,
            },
        )

        group_map[teaching_group.pk] = instructional_group.pk

    for requirement in LessonRequirement.objects.all().iterator():
        instructional_group_id = group_map.get(requirement.teaching_group_id)

        if instructional_group_id is None:
            raise RuntimeError(
                "Could not map LessonRequirement "
                f"{requirement.pk} from TeachingGroup "
                f"{requirement.teaching_group_id}."
            )

        LessonRequirement.objects.filter(pk=requirement.pk).update(
            instructional_group_id=instructional_group_id
        )

class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionalGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('learner_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'instructional_group',
                'ordering': ['teaching_group', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='lessonrequirement',
            options={'ordering': ['instructional_group', 'subject']},
        ),
        migrations.RemoveConstraint(
            model_name='lessonrequirement',
            name='uq_lesson_requirement_term_group_subject',
        ),
        migrations.AddField(
            model_name='instructionalgroup',
            name='teaching_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructional_groups', to='academics.teachinggroup'),
        ),
        migrations.AddField(
            model_name='lessonrequirement',
            name='instructional_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requirements', to='academics.instructionalgroup'),
        ),
        migrations.RunPython(
            code=populate_instructional_groups,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='lessonrequirement',
            constraint=models.UniqueConstraint(fields=('term', 'instructional_group', 'subject'), name='uq_lesson_requirement_term_instructional_group_subject'),
        ),
        migrations.RemoveField(
            model_name='lessonrequirement',
            name='teaching_group',
        ),
        migrations.AddConstraint(
            model_name='instructionalgroup',
            constraint=models.UniqueConstraint(fields=('teaching_group', 'name'), name='uq_instructional_group_teaching_group_name'),
        ),
        migrations.AddConstraint(
            model_name='instructionalgroup',
            constraint=models.UniqueConstraint(fields=('teaching_group', 'code'), name='uq_instructional_group_teaching_group_code'),
        ),
        migrations.AddConstraint(
            model_name='instructionalgroup',
            constraint=models.CheckConstraint(condition=models.Q(('learner_count__gte', 0)), name='ck_instructional_group_learner_count'),
        ),
    ]
