# Generated by Django 6.1 on 2026-08-15 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_teaching_period', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'period',
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('number',), name='uq_period_number'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='ck_period_times')],
            },
        ),
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('version_number', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_versions', to='core.term')),
            ],
            options={
                'db_table': 'timetable_version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('lesson_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='academics.lessonrequirement')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='scheduling.period')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='users.teacher')),
                ('teaching_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='academics.teachinggroup')),
                ('timetable_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='scheduling.timetableversion')),
            ],
            options={
                'db_table': 'timetable_entry',
                'ordering': ['day', 'period__number'],
            },
        ),
        migrations.AddConstraint(
            model_name='timetableversion',
            constraint=models.UniqueConstraint(fields=('term', 'version_number'), name='uq_timetable_version_term_number'),
        ),
        migrations.AddConstraint(
            model_name='timetableversion',
            constraint=models.UniqueConstraint(fields=('term', 'name'), name='uq_timetable_version_term_name'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('timetable_version', 'day', 'period', 'teaching_group'), name='uq_timetable_entry_group_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('timetable_version', 'day', 'period', 'teacher'), name='uq_timetable_entry_teacher_slot'),
        ),
    ]
