# Generated by Django 6.1 on 2026-08-17 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'room_availability',
                'ordering': ['room', 'day', 'period__number'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'teacher_assignment',
                'ordering': ['teacher', 'lesson_requirement'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'teacher_availability',
                'ordering': ['teacher', 'day', 'period__number'],
            },
        ),
        migrations.CreateModel(
            name='TeacherFreeAfternoon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'teacher_free_afternoon',
                'ordering': ['teacher', 'day'],
            },
        ),
        migrations.AddField(
            model_name='period',
            name='part_of_day',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='core.school')),
            ],
            options={
                'db_table': 'room',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='scheduling.room'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['timetable_version', 'day', 'period'], name='ix_timetable_entry_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('timetable_version', 'day', 'period', 'room'), name='uq_timetable_entry_room_slot'),
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_availability', to='scheduling.period'),
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability', to='scheduling.room'),
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_availability', to='core.term'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='lesson_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='academics.lessonrequirement'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_availability', to='scheduling.period'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_availability', to='core.term'),
        ),
        migrations.AddField(
            model_name='teacherfreeafternoon',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='free_afternoons', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='teacherfreeafternoon',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_free_afternoons', to='core.term'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uq_room_school_name'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='uq_room_school_code'),
        ),
        migrations.AddIndex(
            model_name='roomavailability',
            index=models.Index(fields=['term', 'room'], name='ix_room_availability_term_room'),
        ),
        migrations.AddIndex(
            model_name='roomavailability',
            index=models.Index(fields=['term', 'day', 'period'], name='ix_room_availability_slot'),
        ),
        migrations.AddConstraint(
            model_name='roomavailability',
            constraint=models.UniqueConstraint(fields=('term', 'room', 'day', 'period'), name='uq_room_availability_slot'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'lesson_requirement'), name='uq_teacher_assignment_teacher_requirement'),
        ),
        migrations.AddIndex(
            model_name='teacheravailability',
            index=models.Index(fields=['term', 'teacher'], name='ix_teacher_avail_term_teacher'),
        ),
        migrations.AddIndex(
            model_name='teacheravailability',
            index=models.Index(fields=['term', 'day', 'period'], name='ix_teacher_availability_slot'),
        ),
        migrations.AddConstraint(
            model_name='teacheravailability',
            constraint=models.UniqueConstraint(fields=('term', 'teacher', 'day', 'period'), name='uq_teacher_availability_slot'),
        ),
        migrations.AddIndex(
            model_name='teacherfreeafternoon',
            index=models.Index(fields=['term', 'day'], name='ix_teacher_free_term_day'),
        ),
        migrations.AddConstraint(
            model_name='teacherfreeafternoon',
            constraint=models.UniqueConstraint(fields=('term', 'teacher'), name='uq_teacher_free_afternoon_teacher_term'),
        ),
    ]
