# Generated by Django 6.1 on 2026-08-17 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('scheduling', '0002_roomavailability_teacherassignment_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('solver_status', models.CharField(choices=[('NOT_RUN', 'Not Run'), ('FEASIBLE', 'Feasible'), ('OPTIMAL', 'Optimal'), ('INFEASIBLE', 'Infeasible'), ('UNKNOWN', 'Unknown'), ('ERROR', 'Error')], default='NOT_RUN', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('objective_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('statistics', models.JSONField(blank=True, default=dict)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduling_runs', to='core.term')),
                ('timetable_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduling_runs', to='scheduling.timetableversion')),
            ],
            options={
                'db_table': 'scheduling_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Information')], max_length=10)),
                ('category', models.CharField(choices=[('TEACHER_CLASH', 'Teacher Clash'), ('GROUP_CLASH', 'Teaching Group Clash'), ('ROOM_CLASH', 'Room Clash'), ('TEACHER_UNAVAILABLE', 'Teacher Unavailable'), ('ROOM_UNAVAILABLE', 'Room Unavailable'), ('FREE_AFTERNOON_VIOLATION', 'Free Afternoon Violation'), ('MISSING_TEACHER_ASSIGNMENT', 'Missing Teacher Assignment'), ('INVALID_LESSON_REQUIREMENT', 'Invalid Lesson Requirement'), ('INVALID_PERIOD', 'Invalid Period'), ('INVALID_TIMETABLE_ENTRY', 'Invalid Timetable Entry'), ('UNSCHEDULED_LESSON', 'Unscheduled Lesson'), ('CONSTRAINT_VIOLATION', 'Constraint Violation'), ('CONFIGURATION_ERROR', 'Configuration Error'), ('OTHER', 'Other')], max_length=40)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('day', models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validation_results', to='scheduling.period')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validation_results', to='scheduling.room')),
                ('scheduling_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='scheduling.schedulingrun')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validation_results', to='users.teacher')),
                ('teaching_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validation_results', to='academics.teachinggroup')),
                ('timetable_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validation_results', to='scheduling.timetableentry')),
            ],
            options={
                'db_table': 'validation_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='schedulingrun',
            index=models.Index(fields=['term', 'status'], name='ix_scheduling_run_term_status'),
        ),
        migrations.AddIndex(
            model_name='schedulingrun',
            index=models.Index(fields=['timetable_version'], name='ix_scheduling_run_version'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['scheduling_run', 'severity'], name='ix_validation_run_severity'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['scheduling_run', 'category'], name='ix_validation_run_category'),
        ),
    ]
