# Generated by Django 6.1 on 2026-08-22 09:56

import django.db.models.deletion
from django.db import migrations, models


def populate_timetable_instructional_groups(apps, schema_editor):
    TeachingGroup = apps.get_model("academics", "TeachingGroup")
    InstructionalGroup = apps.get_model("academics", "InstructionalGroup")
    TimetableEntry = apps.get_model("scheduling", "TimetableEntry")
    ValidationResult = apps.get_model("scheduling", "ValidationResult")

    group_map = {}

    for teaching_group in TeachingGroup.objects.all().iterator():
        instructional_group = InstructionalGroup.objects.filter(
            teaching_group_id=teaching_group.pk,
            code=teaching_group.code,
        ).first()

        if instructional_group is None:
            raise RuntimeError(
                "Could not find deterministic InstructionalGroup "
                f"for TeachingGroup {teaching_group.pk} "
                f"with code {teaching_group.code!r}."
            )

        group_map[teaching_group.pk] = instructional_group.pk

    for entry in TimetableEntry.objects.all().iterator():
        instructional_group_id = group_map.get(entry.teaching_group_id)

        if instructional_group_id is None:
            raise RuntimeError(
                "Could not map TimetableEntry "
                f"{entry.pk} from TeachingGroup "
                f"{entry.teaching_group_id}."
            )

        TimetableEntry.objects.filter(pk=entry.pk).update(
            instructional_group_id=instructional_group_id
        )

    for result in ValidationResult.objects.filter(
        teaching_group__isnull=False
    ).iterator():
        instructional_group_id = group_map.get(result.teaching_group_id)

        if instructional_group_id is None:
            raise RuntimeError(
                "Could not map ValidationResult "
                f"{result.pk} from TeachingGroup "
                f"{result.teaching_group_id}."
            )

        ValidationResult.objects.filter(pk=result.pk).update(
            instructional_group_id=instructional_group_id
        )

class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_instructionalgroup_alter_lessonrequirement_options_and_more'),
        ('scheduling', '0003_schedulingrun_validationresult_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='uq_timetable_entry_group_slot',
        ),

        migrations.AddField(
            model_name='timetableentry',
            name='instructional_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='academics.instructionalgroup'),
        ),
        migrations.AddField(
            model_name='validationresult',
            name='instructional_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validation_results', to='academics.instructionalgroup'),
        ),
        migrations.RunPython(
            code=populate_timetable_instructional_groups,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('timetable_version', 'day', 'period', 'instructional_group'), name='uq_timetable_entry_group_slot'),
        ),
        migrations.RemoveField(
            model_name='validationresult',
            name='teaching_group',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='teaching_group',
        ),
    ]
