# Generated by Django 6.1 on 2026-09-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_remove_timetableentry_uq_timetable_entry_group_slot_and_more'),
        ('users', '0002_alter_teacher_options_teacher_teacher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='users.teacher'),
        ),
    ]
